version: '3.6'
services:
  search-service:
    build: ./
    command: mvn install dockerfile:build
    container_name: search-service-docker
    image: heazelcast-search-service:1.0.0
    expose:
        - 17600
    ports:
        - "17600:17600"
    logging:
      driver: "json-file"    # for local
    environment:
#        - env=aws-ecs-cluster
         - env=local
    entrypoint:
      - /entrypoint.sh

